import { Document } from 'mongoose';

export interface ICharacter extends Document {
  readonly characterName: string;
  readonly playerName: string;
  readonly age: number;
  readonly weight: number;
  readonly height: number;
  readonly backstory: string;
  readonly alliesAndOrganizations: string;
  readonly race: string;
  readonly class: string;
  readonly level: number;
  readonly experience: number;
  readonly maxHp: number;
  readonly currentHp: number;
  readonly armorClass: number;
  readonly initiative: number;
  readonly speed: number;
  readonly inspiration: number;
  readonly proficiencyBonus: number;
  readonly perception: number;
  readonly hitDice: number;
  readonly savingThrows: boolean;
  readonly deathSaves: boolean;
  readonly skills: number;
  readonly language: string;
  readonly equippedItems: string;
  readonly background: string;
  readonly personality: string;
  readonly ideals: string;
  readonly bonds: string;
  readonly flaws: string;
  readonly alignment: string;
  readonly attackItem: string;
  readonly attackItemBonus: number;
  readonly attackItemDamageType: string;
  readonly attackNotes: string;
  readonly featuresAndTraits: string;
}
